import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/navbar";
import { CounterStoreProvider } from "@/providers/counter-store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialCount = 12;

  return (

    <html lang="en">
      <body>
        <CounterStoreProvider>
          <ClerkProvider>
            <Navbar initialCount={initialCount} />
            {children}
          </ClerkProvider>
        </CounterStoreProvider>


      </body>
    </html>
  );
}
